# Workflow to send master to pypi and tag  the branch:
# You need to edit FOLDER_WITH_VERSION with the folder that has the __version__ value. 

name: master to pypi with comments and tag 

on:
  push:
    branches: [ master ]

jobs:
  call-publish-workflow:
    uses: scipion-em/.github/.github/workflows/publish_and_tag.yml@master
    with:
      folder: emfacilities
    secrets: inherit
